CREATE DATABASE gis;
REVOKE ALL PRIVILEGES ON DATABASE gis FROM public;

CREATE USER gis WITH PASSWORD 'sig';
GRANT ALL PRIVILEGES ON DATABASE gis TO gis;

\c gis
CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;
CREATE EXTENSION postgis_sfcgal;
CREATE EXTENSION pgrouting;
CREATE EXTENSION postgres_fdw;
CREATE EXTENSION pg_trgm;
CREATE EXTENSION btree_gist;
CREATE EXTENSION btree_gin;
