version: '3.4'

x-logging: &_logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "10"

x-node-environment: &_node-environment
  GIS_BUILD_TARGET:
  MAP_USER:
  VHOST_SUFFIX:
  NPM_AUTO_INSTALL: 1

x-node-base: &_node-base
  build:
    args:
      - http_proxy
      - NPM_VERSION=6.7.0
    context: container-scripts
    dockerfile: Dockerfile.node
    network: build
  environment:
    <<: *_node-environment
  image: gis-dev-node
  networks:
    default:
    nginx:
  restart: always

networks:
  build:
    external:
      name: build
  nginx:
    external:
      name: nginx

volumes:
  npm-cache:
  pgdata:
  postgresql-java:

services:
  postgresql:
    build:
      args:
        - http_proxy
      context: container-scripts
      dockerfile: Dockerfile.postgresql
      network: build
    #command: /sbin/my_init
    env_file:
      - ./.env.defaults
    environment:
      - PGDATA=/var/lib/postgresql/data
    image: gis-postgresql
    logging:
      <<: *_logging
    networks:
      - default
    volumes:
      - postgresql-java:/usr/share/java:ro
      - ./etc/postgresql-docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - /srv/docker/gis/postgresql/data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    volumes:
      - /srv/docker/minio/data:/data
    ports:
      - "9000:9000"
    networks:
      - default
      - nginx
    environment:
      - VIRTUAL_HOST=s3.${VHOST_SUFFIX}
      - VIRTUAL_PORT=9000
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    command: server /data

  cantaloupe:
    depends_on:
      - minio
    image: lyrasis/cantaloupe:latest
    environment:
      CANTALOUPE_UID: ${MAP_UID}
      CANTALOUPE_GID: ${MAP_GID}
      DELEGATE_SCRIPT_ENABLED: "true"
      ENDPOINT_ADMIN_ENABLED: "false"
      PRINT_STACK_TRACE_ON_ERROR_PAGES: "false"
      ENDPOINT_IIIF_1_ENABLED: "false"
      ENDPOINT_IIIF_2_ENABLED: "true"
      ENDPOINT_API_ENABLED: "false"
      #SOURCE_STATIC: "HttpSource"
      #
      CACHE_SERVER_TTL_SECONDS: "1296000"
      CACHE_SERVER_WORKER_INTERVAL: "3600"
      CACHE_SERVER_SOURCE_ENABLED: "true"
      CACHE_SERVER_DERIVATIVE_ENABLED: "true"
      CACHE_SERVER_DERIVATIVE: "FilesystemCache"
      CACHE_SERVER_RESOLVE_FIRST: "false"

      JAVA_OPTS: "-Xmx2g"
      PROCESSOR_JP2: "OpenJpegProcessor"
      PROCESSOR_STREAM_RETRIEVAL_STRATEGY: "CacheStrategy"
      LOG_APPLICATION_LEVEL: "warn"

      SOURCE_DELEGATE: "true"
      FILESYSTEMSOURCE_LOOKUP_STRATEGY: "ScriptLookupStrategy"

      HTTPSOURCE_LOOKUP_STRATEGY: "ScriptLookupStrategy"
      HTTPSOURCE_REQUEST_TIMEOUT: "60"

      S3SOURCE_LOOKUP_STRATEGY: "ScriptLookupStrategy"
      S3SOURCE_BUCKET_NAME: "gis-app"
      S3SOURCE_BUCKET_LOCATION: "us-east-1"
      S3SOURCE_ACCESS_KEY_ID: "minio"
      S3SOURCE_SECRET_KEY: "minio123"
      S3SOURCE_ENDPOINT: "http://minio:9000"

      VIRTUAL_HOST: cantaloupe.${VHOST_SUFFIX}
      VIRTUAL_PORT: 8182
    networks:
      - default
      - nginx
    volumes:
      - ./delegates.rb:/cantaloupe/delegates.rb:ro
      - /srv/docker/gis/cantaloupe/cache:/var/cache/cantaloupe
      - /srv/docker/minio/data:/srv/minio:ro

  geoserver:
    build:
      args:
        - http_proxy
        - MAVEN_REPO_MIRROR
      context: .
      dockerfile: Dockerfile.geoserver
      network: build
    depends_on:
      - postgresql
    environment:
      - DOCKER_HOST_IP=/var/run/docker.sock
      - VIRTUAL_HOST=geoserver.${VHOST_SUFFIX}
      - VIRTUAL_PORT=8080
      - NGINX_BASE_URL=http://geoserver.${VHOST_SUFFIX}
    image: gis-geoserver
    labels:
      - com.brainfood.docker.localdev.tool.gs-shell=/usr/local/geoserver-shell/gs-shell
      - com.brainfood.docker.localdev.tool.gs-shell.target_pwd=relative
    logging:
      <<: *_logging
    networks:
      nginx:
      default:
        aliases:
          - geonode
    ports:
      - 8080
    volumes:
      - ./:/srv/app:ro
#      - ./config/epsg_overrides.properties:/geoserver_data/data/user_projections/epsg_overrides.properties:ro

  gdal:
    build:
      args:
        - http_proxy
      context: .
      dockerfile: Dockerfile.gdal
      network: build
    depends_on:
      - postgresql
    env_file:
      - ./.env.defaults
    environment:
      - PG_USE_COPY=1
      - OGR_ENABLE_PARTIAL_REPROJECTION=true
    image: gis-gdal
    labels:
      - com.brainfood.docker.localdev.target_pwd=relative
      - com.brainfood.docker.localdev.target_user=hostuser
      - com.brainfood.docker.localdev.tool.ogrinfo
      - com.brainfood.docker.localdev.tool.ogr2ogr
      - com.brainfood.docker.localdev.tool.osm2pgsql
      - com.brainfood.docker.localdev.tool.shp2pgsql
      - com.brainfood.docker.localdev.tool.python
      - com.brainfood.docker.localdev.tool.read_location_data=/srv/app/android_location_converter/read_location_data.py
    networks:
      - default
    volumes:
      - .:/srv/app
    working_dir: /srv/app

  gis-api:
    <<: *_node-base
    command: ['gosu', 'node', 'npm', 'run', 'dev']
    environment:
      <<: *_node-environment
      VIRTUAL_HOST: api.${VHOST_SUFFIX}
      CALCULATE_ROUTE_CONCURRENCY:
      GOOGLE_MAPS_API_KEY:
    volumes:
      - npm-cache:/home/node/.npm/_cacache
      - ./gis-api:/srv/app
      - ./etc/gis-api:/srv/app/etc:ro
      - ./data/exports:/srv/app/exports
      - ./data/geojson:/srv/app/geojson
    working_dir: /srv/app

  web-frontend:
    <<: *_node-base
    command: ['gosu', 'node', 'npm', 'run', 'dev']
    environment:
      <<: *_node-environment
      GIS_BUILD_TARGET:
      GIS_GA_ID:
      HOST: 0.0.0.0
      VIRTUAL_HOST: www.${VHOST_SUFFIX},${VHOST_SUFFIX}
    volumes:
      - npm-cache:/home/node/.npm/_cacache
      - .:/srv/app
      - ./gis-frontend:/srv/app/git-frontend
    working_dir: /srv/app/git-frontend

  helper-node:
    <<: *_node-base
    command: ["sleep", "infinity"]
    depends_on:
      - postgresql
    labels:
      - com.brainfood.docker.localdev.tool.gis-iiif-loader=/srv/app/gis-iiif-loader/iiif-loader.js
    volumes:
      - npm-cache:/home/node/.npm/_cacache
      - ./.localdev/npm-prefix:/home/node/.npm-prefix:rw
      - .:/srv/app
