CREATE DATABASE perm;
REVOKE ALL PRIVILEGES ON DATABASE perm FROM public;

CREATE USER perm WITH PASSWORD 'mrep';
GRANT ALL PRIVILEGES ON DATABASE perm TO perm;

\c perm
CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;
CREATE EXTENSION postgis_sfcgal;
CREATE EXTENSION pg_trgm;

